name: sahibullab
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.16
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.1
  get: ^4.6.1
  google_fonts: ^2.2.0
  http: ^0.13.4
  iconly: ^1.0.1
  responsive_builder: ^0.4.2
  unicons: ^2.1.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/icons/
