// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCevA4myxZh2hAS0Ofk95CLgTtNHdW41Vc',
    appId: '1:98953503316:web:b14f40bbae38593b1b43c1',
    messagingSenderId: '98953503316',
    projectId: 'sahibulnf',
    authDomain: 'sahibulnf.firebaseapp.com',
    storageBucket: 'sahibulnf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2XDDdmF3kJE4GvvIDfMPHP-GgeGNjmxs',
    appId: '1:98953503316:android:162768f847593f021b43c1',
    messagingSenderId: '98953503316',
    projectId: 'sahibulnf',
    storageBucket: 'sahibulnf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVNwntxle-UF2W90zZfILltL8Ari2m-Sw',
    appId: '1:98953503316:ios:d053abffacd6038e1b43c1',
    messagingSenderId: '98953503316',
    projectId: 'sahibulnf',
    storageBucket: 'sahibulnf.appspot.com',
    iosClientId: '98953503316-io1lb7q41s0n33h6cs4n921froav7nup.apps.googleusercontent.com',
    iosBundleId: 'com.sahibulnf.myPortfolio',
  );
}
