// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiyIvOh4VF_XCq7tN5VB_HXpWKOvkkmRE',
    appId: '1:372923294453:web:e7162a1a0da7500a2c1bbc',
    messagingSenderId: '372923294453',
    projectId: 'sahibulnf-cb5ce',
    authDomain: 'sahibulnf-cb5ce.firebaseapp.com',
    storageBucket: 'sahibulnf-cb5ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhjkX9C2had-aiO8Xow6tUDSvjBuCR2Z4',
    appId: '1:372923294453:android:7dcb7e8c953e24572c1bbc',
    messagingSenderId: '372923294453',
    projectId: 'sahibulnf-cb5ce',
    storageBucket: 'sahibulnf-cb5ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzg8UfdrSvyPAZrF_A2zkQB7hth5CQFlE',
    appId: '1:372923294453:ios:0a38ed28daf3ee8c2c1bbc',
    messagingSenderId: '372923294453',
    projectId: 'sahibulnf-cb5ce',
    storageBucket: 'sahibulnf-cb5ce.appspot.com',
    iosClientId: '372923294453-cgc00qc151jn9bbh34vdsnknqdm07cev.apps.googleusercontent.com',
    iosBundleId: 'com.sahibulnf.myPortfolio',
  );
}
